name = "Bruno Steven Ramirez Silva"
rol = "Comunicador Audiovisual"
email = "brunoasteven@gmail.com"
phone = "+51 982 713 325"
birthday = "24 de Octubre del 2000"
location = "Lima, Perú"
avatar = "./config/assets/avatars/my-avatar.png"
username = "brunoasteven" # <-- github user name
googlemaps = "https://www.google.com/maps/@-12.0830636,-77.0101116,3a,75y,277.87h,90t/data=!3m6!1e1!3m4!1s5yqhMYg0t-ishLybeZsk_w!2e0!7i13312!8i6656?entry=ttu" 
presentation = """
Hola ! Como profesional de la Comunicación Audiovisual, he tenido el privilegio de sumergirme en diversos proyectos cinematográficos que han enriquecido mi experiencia y consolidado mi amor por este arte. 

Lo que más disfruto es trabajar codo a codo con personas apasionadas y talentosas, contribuyendo al éxito conjunto de cada proyecto. Mi enfoque es siempre proactivo y orientado al logro de objetivos, ya que creo firmemente en la importancia de la colaboración para alcanzar resultados excepcionales.

Además, soy un firme creyente en el aprendizaje continuo. Siempre estoy buscando nuevas oportunidades para crecer y mejorar, explorando las últimas tendencias y tecnologías en la industria. Cada proyecto es una nueva aventura, una oportunidad para aprender y crecer, y estoy emocionado por lo que el futuro de la Comunicación Audiovisual tiene reservado para mí.

¡Estoy ansioso por conectar con personas apasionadas que compartan la misma pasión por el cine y estén listas para embarcarse en emocionantes proyectos juntos!

"""
